### ISSUE TITLE
Doc site is down

### ISSUE THREAD

**Issue by brandonpittman** [ivebencrazy/johnny_decimal#12]
![CleanShot 2023-01-04 at 10 20 06@2x](https://user-images.githubusercontent.com/967145/210467221-ab752297-8930-45f1-93f1-5709835f4554.png)

Sorry for the issue. Not sure else how to let you know.

**Comment by bpevs** [comment]
🙏 No need to apologize for catching something I missed! I appreciate the lookin out!

Looks like ~cloudflare~ I changed some cloudflare configuration setting... all my cloudflare-pages backed `*.bpev.me` sites via are baroque... 😑

Will close when back to normal.  For now, pointed the repo at the direct pages url: [johnny-decimal.pages.dev](https://johnny-decimal.pages.dev)
