### ISSUE TITLE
Add Support for non-zsh shells

### ISSUE THREAD

**Issue by bpevs** [ivebencrazy/johnny_decimal#5]
esp check usage within ~windows~ and bash.

- [x] Bash
~- [ ] Windows~

**Comment by bpevs** [comment]
https://github.com/ivebencrazy/johnny_decimal/commit/2dca31aa2340ea879c3121a866b95f3717cfbcba#diff-3d98c5cd4ef066ef55054742e106f6e00f62e59605cfc3e21fabb9f0f1cf1228

adds structure for this. ~Presumably works for bash.~
^ Confirmed works for bash via `chsh -s /bin/bash`.  Works, and switch back to `chsh -s /bin/zsh` after.

Need to check what changes are necessary for windows.

**Comment by bpevs** [comment]
Looks like for Windows, we will need better integration with [profiles](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7)?  The changes look like a bit more than I expected, though.  When I try to run, even home is undefined...

 `Uncaught Error: $HOME is undefined`

So I think I will push this to post-1.0.0, and just say that Windows is not currently supported.

**Comment by bpevs** [comment]
Will make separate issue for Windows.

**Comment by brandonpittman** [comment]
Location changing doesn't work with Fish.
