### ISSUE TITLE
Location changing doesn't work with Fish.

### ISSUE THREAD

**Issue by bpevs** [ivebencrazy/johnny_decimal#7]
Location changing doesn't work with Fish.

_Originally posted by @brandonpittman in https://github.com/bpevs/johnny_decimal/issues/5#issuecomment-1214321385_

**Comment by bpevs** [comment]
Fish works a bit differently, and I'm p sure I didn't ever bother to fully implement, since I don't use it... but lemme see if I can make this work for you @brandonpittman

In the meantime, the dir changing is literally just this bash script: https://github.com/bpevs/johnny_decimal/blob/main/source/shell/main.sh

idk the fish ecosystem so well, but if there's a way to add it (from quick search, maybe via something like [bass](https://github.com/edc/bass) ?), then it'd probably work.

Would also need to add something like `set JD_HOME $HOME/my_root_jd_dir` to config.fish

**Comment by brandonpittman** [comment]
I posted a Fish script that I've been using in the JD forum post that you announced this program.

https://forum.johnnydecimal.com/t/i-made-a-j-d-javascript-cli/474/3

```fish
function jd
  set -l JD_HOME $HOME/Documents
  set -l SEARCH $argv[1]

  if string match -rq '^(?<category>[0-9]{2})$' $SEARCH
    # Matches category regex: `dd`. Navigate to category
    set -l CATEGORY (find -E $JD_HOME -regex ".*/$SEARCH .*" -depth 2 -type d) 2>/dev/null;

    test -z "$CATEGORY" && cd $JD_HOME && return 1
    cd $CATEGORY
  else if string match -rq '^(?<category>[0-9]{2})\.(?<id>[0-9]{2,4})$' $SEARCH
    # Matches id regex: `dd.dd`. Navigate to id
    set -l CATEGORY (find -E $JD_HOME -regex ".*/$category .*" -depth 2 -type d) 2>/dev/null;
    set -l ID (find -E $CATEGORY -regex ".*/$id ?.*" -type d ) 2>/dev/null;

    test -z "$ID" && cd $JD_HOME && return 1

    cd $ID
  else
    # No arg for cd. Navigate to root.
    cd $JD_HOME 2>/dev/null;
  end
end
```

Currently, the Deno program finds the fish config correctly, but adds bash/zsh code to it.


Tried `bass`, and while I get no errors, the `jd` command doesn't change to anywhere.

**Comment by bpevs** [comment]
Oh I missed this!  This is very helpful!  I was trying yesterday, but was having some trouble translating this script to work correctly heh.  I'll try integrating this one tmrw.

**Comment by bpevs** [comment]
incomplete, but work will be done in https://github.com/bpevs/johnny_decimal/tree/feat/fish

**Comment by brandonpittman** [comment]
Thanks. If you need any Fish scripting help, let me know.

**Comment by bpevs** [comment]
Should work with #8
