### ISSUE TITLE
Fish script broken for `category/id` search

### ISSUE THREAD

**Issue by brandonpittman** [ivebencrazy/johnny_decimal#9]
https://github.com/bpevs/johnny_decimal/blob/cf480c4df7b200d5a8e847d4fcf4de99ae749f00/source/shell/main.fish#L15

This isn't working for me. If I change `$argv` on this line to:

```fish
"$JD_HOME/.*/$category.*/$id.*"
```

it works. Otherwise, it's as if you're using:

```fish
"$JD_HOME/.*/.*/$category\.$id.*"
```

**Comment by bpevs** [comment]
```sh
"$JD_HOME/.*/$category.*/$id.*"
```

^ @brandonpittman actually this doesn't work for me.  How do you have your filesystem setup?  I have it like:

```
10-19 AREA_NAME/10 CATEGORY_NAME/10.09 ID_NAME/my_content_here
```

I think this suggested regex expects ID to be two digits?  (like `09`)?  From what I see, JohnnyDecimal usually prefers the [ full id](https://johnnydecimal.com/concepts/tracking-your-numbers/), so if this is not the way you have it setup, then I'd consider this more just a personal choice, and would probably prefer users edit the script as you just have.

If you do have the full id in the dir names, maybe I'm missing something. If I update the regex to:

```
"$JD_HOME/.*/$category.*/$category\.$id.*"
```

it works for me.  I don't mind updating to this.

**Comment by brandonpittman** [comment]
Ah, I'm not including the category number in the ID folder name. Just doing this:

`10-19 AREA_NAME/10 CATEGORY_NAME/09 ID_NAME/my_content_here`

Since I wasn't following the example on JD's site, I'll close this. Sorry.
